//! git-gears-c's GraphQL queries
//! as structures and snprintf-style functions
//! DO NOT EDIT - this file is autogenerated.
//! Run `genie generate` or `make generate` to re-generate.

#include "github_graphqlutils.h"
#include "github_graphql.h"
#include "gitlab_graphql.h"
#include "stb_printf.h"

int snprintJsonVars_GithubQueryIssueGraphql(char* buf, int count, const GithubQueryIssueGraphql* vars)
{
	return stbsp_snprintf(buf, count,
						  "{"
						  " \"_name\": \"%s\","
						  " \"_number\": %i,"
						  " \"_owner\": \"%s\""
						  "}",
						  vars->name, vars->number, vars->owner);
}

int snprintJsonRequest_GithubQueryIssueGraphql(char* buf, int count, const GithubQueryIssueGraphql* vars)
{
	return stbsp_snprintf(buf, count,
						  "{"
						  "\"variables\": {"
						  " \"_name\": \"%s\","
						  " \"_number\": %i,"
						  " \"_owner\": \"%s\""
						  "}"
						  ","
						  "\"query\": \"%s\""
						  "} \n",
						  vars->name, vars->number, vars->owner, g_github_query_issue_graphql_de);
}

int snprintJsonVars_GithubQueryGistsGraphql(char* buf, int count, const GithubQueryGistsGraphql* vars)
{
	return stbsp_snprintf(buf, count,
						  "{"
						  " \"_count\": %i,"
						  " \"_owner\": \"%s\""
						  "}",
						  vars->count, vars->owner);
}

int snprintJsonRequest_GithubQueryGistsGraphql(char* buf, int count, const GithubQueryGistsGraphql* vars)
{
	return stbsp_snprintf(buf, count,
						  "{"
						  "\"variables\": {"
						  " \"_count\": %i,"
						  " \"_owner\": \"%s\""
						  "}"
						  ","
						  "\"query\": \"%s\""
						  "} \n",
						  vars->count, vars->owner, g_github_query_gists_graphql_de);
}

int snprintJsonVars_GithubQueryOrganizationGraphql(char* buf, int count, const GithubQueryOrganizationGraphql* vars)
{
	return stbsp_snprintf(buf, count,
						  "{"
						  " \"_login\": \"%s\""
						  "}",
						  vars->login);
}

int snprintJsonRequest_GithubQueryOrganizationGraphql(char* buf, int count, const GithubQueryOrganizationGraphql* vars)
{
	return stbsp_snprintf(buf, count,
						  "{"
						  "\"variables\": {"
						  " \"_login\": \"%s\""
						  "}"
						  ","
						  "\"query\": \"%s\""
						  "} \n",
						  vars->login, g_github_query_organization_graphql_de);
}

int snprintJsonVars_GithubQueryPullrequestGraphql(char* buf, int count, const GithubQueryPullrequestGraphql* vars)
{
	return stbsp_snprintf(buf, count,
						  "{"
						  " \"_branch\": \"%s\","
						  " \"_name\": \"%s\","
						  " \"_owner\": \"%s\""
						  "}",
						  vars->branch, vars->name, vars->owner);
}

int snprintJsonRequest_GithubQueryPullrequestGraphql(char* buf, int count, const GithubQueryPullrequestGraphql* vars)
{
	return stbsp_snprintf(buf, count,
						  "{"
						  "\"variables\": {"
						  " \"_branch\": \"%s\","
						  " \"_name\": \"%s\","
						  " \"_owner\": \"%s\""
						  "}"
						  ","
						  "\"query\": \"%s\""
						  "} \n",
						  vars->branch, vars->name, vars->owner, g_github_query_pullrequest_graphql_de);
}

int snprintJsonVars_GithubMutationCreateIssueGraphql(char* buf, int count, const GithubMutationCreateIssueGraphql* vars)
{
	return stbsp_snprintf(buf, count,
						  "{"
						  " \"_body\": \"%s\","
						  " \"_mutationId\": \"%s\","
						  " \"_repositoryId\": \"%s\","
						  " \"_title\": \"%s\""
						  "}",
						  vars->body, vars->mutationId, vars->repositoryId, vars->title);
}

int snprintJsonRequest_GithubMutationCreateIssueGraphql(char* buf, int count,
														const GithubMutationCreateIssueGraphql* vars)
{
	return stbsp_snprintf(buf, count,
						  "{"
						  "\"variables\": {"
						  " \"_body\": \"%s\","
						  " \"_mutationId\": \"%s\","
						  " \"_repositoryId\": \"%s\","
						  " \"_title\": \"%s\""
						  "}"
						  ","
						  "\"query\": \"%s\""
						  "} \n",
						  vars->body, vars->mutationId, vars->repositoryId, vars->title,
						  g_github_mutation_create_issue_graphql_de);
}

int snprintJsonVars_GithubQueryPullrequestsGraphql(char* buf, int count, const GithubQueryPullrequestsGraphql* vars)
{
	return stbsp_snprintf(buf, count,
						  "{"
						  " \"_count\": %i,"
						  " \"_name\": \"%s\","
						  " \"_owner\": \"%s\""
						  "}",
						  vars->count, vars->name, vars->owner);
}

int snprintJsonRequest_GithubQueryPullrequestsGraphql(char* buf, int count, const GithubQueryPullrequestsGraphql* vars)
{
	return stbsp_snprintf(buf, count,
						  "{"
						  "\"variables\": {"
						  " \"_count\": %i,"
						  " \"_name\": \"%s\","
						  " \"_owner\": \"%s\""
						  "}"
						  ","
						  "\"query\": \"%s\""
						  "} \n",
						  vars->count, vars->name, vars->owner, g_github_query_pullrequests_graphql_de);
}

int snprintJsonRequest_GithubQueryViewerGraphql(char* buf, int count)
{
	return stbsp_snprintf(buf, count,
						  "{"
						  "\"query\": \"%s\""
						  "} \n",
						  g_github_query_viewer_graphql_de);
}

int snprintJsonVars_GithubMutationCreatePullrequestGraphql(char* buf, int count,
														   const GithubMutationCreatePullrequestGraphql* vars)
{
	return stbsp_snprintf(buf, count,
						  "{"
						  " \"_body\": \"%s\","
						  " \"_branch\": \"%s\","
						  " \"_mutationId\": \"%s\","
						  " \"_repositoryId\": \"%s\","
						  " \"_targetBranch\": \"%s\","
						  " \"_title\": \"%s\""
						  "}",
						  vars->body, vars->branch, vars->mutationId, vars->repositoryId, vars->targetBranch,
						  vars->title);
}

int snprintJsonRequest_GithubMutationCreatePullrequestGraphql(char* buf, int count,
															  const GithubMutationCreatePullrequestGraphql* vars)
{
	return stbsp_snprintf(buf, count,
						  "{"
						  "\"variables\": {"
						  " \"_body\": \"%s\","
						  " \"_branch\": \"%s\","
						  " \"_mutationId\": \"%s\","
						  " \"_repositoryId\": \"%s\","
						  " \"_targetBranch\": \"%s\","
						  " \"_title\": \"%s\""
						  "}"
						  ","
						  "\"query\": \"%s\""
						  "} \n",
						  vars->body, vars->branch, vars->mutationId, vars->repositoryId, vars->targetBranch,
						  vars->title, g_github_mutation_create_pullrequest_graphql_de);
}

int snprintJsonVars_GithubQueryRepositoriesGraphql(char* buf, int count, const GithubQueryRepositoriesGraphql* vars)
{
	return stbsp_snprintf(buf, count,
						  "{"
						  " \"_count\": %i,"
						  " \"_owner\": \"%s\""
						  "}",
						  vars->count, vars->owner);
}

int snprintJsonRequest_GithubQueryRepositoriesGraphql(char* buf, int count, const GithubQueryRepositoriesGraphql* vars)
{
	return stbsp_snprintf(buf, count,
						  "{"
						  "\"variables\": {"
						  " \"_count\": %i,"
						  " \"_owner\": \"%s\""
						  "}"
						  ","
						  "\"query\": \"%s\""
						  "} \n",
						  vars->count, vars->owner, g_github_query_repositories_graphql_de);
}

int snprintJsonVars_GithubQueryOwnerGraphql(char* buf, int count, const GithubQueryOwnerGraphql* vars)
{
	return stbsp_snprintf(buf, count,
						  "{"
						  " \"_login\": \"%s\""
						  "}",
						  vars->login);
}

int snprintJsonRequest_GithubQueryOwnerGraphql(char* buf, int count, const GithubQueryOwnerGraphql* vars)
{
	return stbsp_snprintf(buf, count,
						  "{"
						  "\"variables\": {"
						  " \"_login\": \"%s\""
						  "}"
						  ","
						  "\"query\": \"%s\""
						  "} \n",
						  vars->login, g_github_query_owner_graphql_de);
}

int snprintJsonVars_GithubQueryGistGraphql(char* buf, int count, const GithubQueryGistGraphql* vars)
{
	return stbsp_snprintf(buf, count,
						  "{"
						  " \"_name\": \"%s\","
						  " \"_owner\": \"%s\""
						  "}",
						  vars->name, vars->owner);
}

int snprintJsonRequest_GithubQueryGistGraphql(char* buf, int count, const GithubQueryGistGraphql* vars)
{
	return stbsp_snprintf(buf, count,
						  "{"
						  "\"variables\": {"
						  " \"_name\": \"%s\","
						  " \"_owner\": \"%s\""
						  "}"
						  ","
						  "\"query\": \"%s\""
						  "} \n",
						  vars->name, vars->owner, g_github_query_gist_graphql_de);
}

int snprintJsonVars_GithubQueryUserGraphql(char* buf, int count, const GithubQueryUserGraphql* vars)
{
	return stbsp_snprintf(buf, count,
						  "{"
						  " \"_login\": \"%s\""
						  "}",
						  vars->login);
}

int snprintJsonRequest_GithubQueryUserGraphql(char* buf, int count, const GithubQueryUserGraphql* vars)
{
	return stbsp_snprintf(buf, count,
						  "{"
						  "\"variables\": {"
						  " \"_login\": \"%s\""
						  "}"
						  ","
						  "\"query\": \"%s\""
						  "} \n",
						  vars->login, g_github_query_user_graphql_de);
}

int snprintJsonVars_GithubQueryIssuesGraphql(char* buf, int count, const GithubQueryIssuesGraphql* vars)
{
	return stbsp_snprintf(buf, count,
						  "{"
						  " \"_count\": %i,"
						  " \"_name\": \"%s\","
						  " \"_owner\": \"%s\""
						  "}",
						  vars->count, vars->name, vars->owner);
}

int snprintJsonRequest_GithubQueryIssuesGraphql(char* buf, int count, const GithubQueryIssuesGraphql* vars)
{
	return stbsp_snprintf(buf, count,
						  "{"
						  "\"variables\": {"
						  " \"_count\": %i,"
						  " \"_name\": \"%s\","
						  " \"_owner\": \"%s\""
						  "}"
						  ","
						  "\"query\": \"%s\""
						  "} \n",
						  vars->count, vars->name, vars->owner, g_github_query_issues_graphql_de);
}

int snprintJsonVars_GithubMutationCreateRepositoryGraphql(char* buf, int count,
														  const GithubMutationCreateRepositoryGraphql* vars)
{
	return stbsp_snprintf(buf, count,
						  "{"
						  " \"_description\": \"%s\","
						  " \"_homepageUrl\": \"%s\","
						  " \"_mutationId\": \"%s\","
						  " \"_name\": \"%s\","
						  " \"_ownerId\": \"%s\","
						  " \"_visibility\": \"%s\""
						  "}",
						  vars->description, vars->homepageUrl, vars->mutationId, vars->name, vars->ownerId,
						  vars->visibility);
}

int snprintJsonRequest_GithubMutationCreateRepositoryGraphql(char* buf, int count,
															 const GithubMutationCreateRepositoryGraphql* vars)
{
	return stbsp_snprintf(buf, count,
						  "{"
						  "\"variables\": {"
						  " \"_description\": \"%s\","
						  " \"_homepageUrl\": \"%s\","
						  " \"_mutationId\": \"%s\","
						  " \"_name\": \"%s\","
						  " \"_ownerId\": \"%s\","
						  " \"_visibility\": \"%s\""
						  "}"
						  ","
						  "\"query\": \"%s\""
						  "} \n",
						  vars->description, vars->homepageUrl, vars->mutationId, vars->name, vars->ownerId,
						  vars->visibility, g_github_mutation_create_repository_graphql_de);
}

int snprintJsonVars_GithubQueryRepositoryGraphql(char* buf, int count, const GithubQueryRepositoryGraphql* vars)
{
	return stbsp_snprintf(buf, count,
						  "{"
						  " \"_name\": \"%s\","
						  " \"_owner\": \"%s\""
						  "}",
						  vars->name, vars->owner);
}

int snprintJsonRequest_GithubQueryRepositoryGraphql(char* buf, int count, const GithubQueryRepositoryGraphql* vars)
{
	return stbsp_snprintf(buf, count,
						  "{"
						  "\"variables\": {"
						  " \"_name\": \"%s\","
						  " \"_owner\": \"%s\""
						  "}"
						  ","
						  "\"query\": \"%s\""
						  "} \n",
						  vars->name, vars->owner, g_github_query_repository_graphql_de);
}
