//! git-gears-c's REST queries
//! as structures and snprintf-style functions
//! DO NOT EDIT - this file is autogenerated.
//! Run `genie generate` or `make generate` to re-generate.

#ifndef GEARS_REQUESTS_GITHUB_RESTUTILS_H_INC
#define GEARS_REQUESTS_GITHUB_RESTUTILS_H_INC

#include <stdbool.h>

//! snprint url
int snprintUrl_GithubMutationCreateGistRoute(char* buf, int count, const char* endpointUrl);

//! rest data
typedef struct GithubMutationCreateGistJson
{
	const char* body;
	const char* description;
	bool isPublic;
	const char* title;
} GithubMutationCreateGistJson;

//! snprint rest JSON
int snprintRestJson_GithubMutationCreateGistJson(char* buf, int count, const GithubMutationCreateGistJson* vars);


#endif // GEARS_REQUESTS_GITHUB_RESTUTILS_H_INC
