//! git-gears-c's GraphQL queries, as static data buffers.
//! DO NOT EDIT - this file is autogenerated.
//! Run `genie embed` or `make embed` to re-generate.

#define INCBIN_PREFIX g_
#define INCBIN_STYLE INCBIN_STYLE_SNAKE
#include "incbin.h"

INCBIN(github_query_issue_graphql, "requests/github/query_issue.graphql");
const char* g_github_query_issue_graphql_de = "\\nquery($_owner: String!, $_name: String!, $_number: Int!)\\n{\\n repository(owner: $_owner, name: $_name)\\n {\\n  id,\\n  name,\\n  url,\\n  issue(number: $_number)\\n  {\\n   number,\\n   bodyText,\\n   state,\\n   title,\\n   url,\\n  }\\n }\\n}\\n";

INCBIN(github_query_gists_graphql, "requests/github/query_gists.graphql");
const char* g_github_query_gists_graphql_de = "\\nquery($_owner: String!, $_count: Int!)\\n{\\n user(login: $_owner)\\n {\\n  gists(first: $_count)\\n  {\\n   nodes\\n   {\\n    id,\\n    name,\\n    description,\\n    createdAt,\\n    pushedAt,\\n    files\\n    {\\n     name,\\n     text,\\n    }\\n   }\\n  }\\n }\\n}\\n";

INCBIN(github_query_organization_graphql, "requests/github/query_organization.graphql");
const char* g_github_query_organization_graphql_de = "\\nquery($_login: String!)\\n{\\n organization(login: $_login)\\n {\\n  id,\\n  name,\\n  login,\\n  email,\\n  url,\\n  description\\n\\n  projectsUrl,\\n  websiteUrl,\\n }\\n}\\n";

INCBIN(github_query_pullrequest_graphql, "requests/github/query_pullrequest.graphql");
const char* g_github_query_pullrequest_graphql_de = "\\nquery($_owner: String!, $_name: String!, $_branch: String!)\\n{\\n repository(owner: $_owner, name: $_name)\\n {\\n  id,\\n  name,\\n  url,\\n  pullRequests(headRefName: $_branch, orderBy: {direction : DESC, field : UPDATED_AT}, first : 1)\\n  {\\n   nodes\\n   {\\n    baseRefName,\\n    headRefName,\\n    number,\\n    bodyText,\\n    permalink,\\n    resourcePath,\\n    state,\\n    title,\\n    url,\\n   }\\n  }\\n }\\n}\\n";

INCBIN(github_mutation_create_issue_graphql, "requests/github/mutation_create_issue.graphql");
const char* g_github_mutation_create_issue_graphql_de = "\\nmutation($_mutationId: String!, $_repositoryId: ID!, $_title: String!, $_body: String!)\\n{\\n createIssue(input: {\\n  clientMutationId: $_mutationId,\\n  title: $_title,\\n  body: $_body,\\n  repositoryId: $_repositoryId,\\n })\\n {\\n  clientMutationId,\\n  issue\\n  {\\n   number,\\n   bodyText,\\n   state,\\n   title,\\n   url,\\n  }\\n }\\n}\\n";

INCBIN(github_query_pullrequests_graphql, "requests/github/query_pullrequests.graphql");
const char* g_github_query_pullrequests_graphql_de = "\\nquery($_owner: String!, $_name: String!, $_count: Int !)\\n{\\n repository(owner: $_owner, name: $_name)\\n {\\n  id,\\n  name,\\n  url,\\n  pullRequests(orderBy: {direction : DESC, field : UPDATED_AT}, first: $_count)\\n  {\\n   nodes\\n   {\\n    baseRefName,\\n    headRefName,\\n    number,\\n    bodyText,\\n    permalink,\\n    resourcePath,\\n    state,\\n    title,\\n    url,\\n   }\\n  }\\n }\\n}\\n";

INCBIN(github_query_viewer_graphql, "requests/github/query_viewer.graphql");
const char* g_github_query_viewer_graphql_de = "\\nquery\\n{\\n viewer\\n {\\n  login\\n }\\n}\\n";

INCBIN(github_mutation_create_pullrequest_graphql, "requests/github/mutation_create_pullrequest.graphql");
const char* g_github_mutation_create_pullrequest_graphql_de = "\\nmutation($_mutationId: String!,\\n   $_repositoryId: ID!,\\n   $_branch: String!\\n   $_targetBranch: String!,\\n   $_title: String!,\\n   $_body: String!)\\n{\\n createPullRequest(input: {\\n  clientMutationId: $_mutationId,\\n  repositoryId: $_repositoryId,\\n  headRefName: $_branch,\\n  baseRefName: $_targetBranch,\\n  title: $_title,\\n  body: $_body,\\n })\\n {\\n  clientMutationId,\\n  pullRequest\\n  {\\n   baseRefName,\\n   headRefName,\\n   number,\\n   bodyText,\\n   permalink,\\n   resourcePath,\\n   state,\\n   title,\\n   url,\\n  }\\n }\\n}\\n";

INCBIN(github_query_repositories_graphql, "requests/github/query_repositories.graphql");
const char* g_github_query_repositories_graphql_de = "\\nquery($_owner: String!, $_count: Int!)\\n{\\n user(login: $_owner)\\n {\\n  repositoriesContributedTo(first: $_count)\\n  {\\n   nodes\\n   {\\n    id,\\n    url,\\n    name,\\n    description,\\n    homepageUrl,\\n    nameWithOwner,\\n    createdAt,\\n    pushedAt,\\n   }\\n  }\\n }\\n}\\n";

INCBIN(github_query_owner_graphql, "requests/github/query_owner.graphql");
const char* g_github_query_owner_graphql_de = "\\nquery($_login: String!)\\n{\\n organization(login: $_login)\\n {\\n  id,\\n  name,\\n  login,\\n  email,\\n  url,\\n }\\n user(login: $_login)\\n {\\n  id,\\n  name,\\n  login,\\n  email,\\n  url,\\n }\\n}\\n";

INCBIN(github_query_gist_graphql, "requests/github/query_gist.graphql");
const char* g_github_query_gist_graphql_de = "\\nquery($_owner: String!, $_name:String!)\\n{\\n user(login: $_owner)\\n {\\n  gist(name:$_name)\\n  {\\n   id,\\n   name,\\n   description,\\n   createdAt,\\n   pushedAt,\\n   files\\n   {\\n    name,\\n    text,\\n   }\\n  }\\n }\\n}\\n";

INCBIN(github_query_user_graphql, "requests/github/query_user.graphql");
const char* g_github_query_user_graphql_de = "\\nquery($_login: String!)\\n{\\n user(login: $_login)\\n {\\n  id,\\n  name,\\n  login,\\n  email,\\n  url,\\n\\n  bio,\\n  company,\\n  websiteUrl,\\n }\\n}\\n";

INCBIN(github_query_issues_graphql, "requests/github/query_issues.graphql");
const char* g_github_query_issues_graphql_de = "\\nquery($_owner: String!, $_name: String!, $_count: Int !)\\n{\\n repository(owner: $_owner, name: $_name)\\n {\\n  id,\\n  name,\\n  url,\\n  issues(first: $_count)\\n  {\\n   nodes\\n   {\\n    number,\\n    bodyText,\\n    state,\\n    title,\\n    url,\\n   }\\n  }\\n }\\n}\\n";

INCBIN(github_mutation_create_repository_graphql, "requests/github/mutation_create_repository.graphql");
const char* g_github_mutation_create_repository_graphql_de = "\\nmutation($_mutationId: String!,\\n   $_ownerId: ID!,\\n   $_name: String!,\\n   $_visibility: RepositoryVisibility!,\\n   $_description: String,\\n   $_homepageUrl: URI)\\n{\\n createRepository(input: {\\n  clientMutationId: $_mutationId,\\n  ownerId: $_ownerId,\\n  name: $_name,\\n  visibility: $_visibility,\\n  description: $_description,\\n  homepageUrl: $_homepageUrl,\\n })\\n {\\n  clientMutationId,\\n  repository\\n  {\\n   id,\\n   url,\\n   name,\\n   description,\\n   homepageUrl,\\n   nameWithOwner,\\n   createdAt,\\n   pushedAt,\\n  }\\n }\\n}\\n";

INCBIN(github_query_repository_graphql, "requests/github/query_repository.graphql");
const char* g_github_query_repository_graphql_de = "\\nquery($_owner: String!, $_name: String!)\\n{\\n repository(owner: $_owner, name: $_name)\\n {\\n  id,\\n  url,\\n  name,\\n  description,\\n  homepageUrl,\\n  nameWithOwner,\\n  createdAt,\\n  pushedAt,\\n }\\n}\\n";

