//! git-gears-c's GraphQL queries, as static data buffers.
//! DO NOT EDIT - this file is autogenerated.
//! Run `genie embed` or `make embed` to re-generate.

#ifndef GEARS_REQUESTS_GITHUB_GRAPHQL_H_INC
#define GEARS_REQUESTS_GITHUB_GRAPHQL_H_INC

#define INCBIN_PREFIX g_
#define INCBIN_STYLE INCBIN_STYLE_SNAKE
#include "incbin.h"

//! contents of requests/github/query_issue.graphql
INCBIN_EXTERN(github_query_issue_graphql);
const char* g_github_query_issue_graphql_de;

//! contents of requests/github/query_gists.graphql
INCBIN_EXTERN(github_query_gists_graphql);
const char* g_github_query_gists_graphql_de;

//! contents of requests/github/query_organization.graphql
INCBIN_EXTERN(github_query_organization_graphql);
const char* g_github_query_organization_graphql_de;

//! contents of requests/github/query_pullrequest.graphql
INCBIN_EXTERN(github_query_pullrequest_graphql);
const char* g_github_query_pullrequest_graphql_de;

//! contents of requests/github/mutation_create_issue.graphql
INCBIN_EXTERN(github_mutation_create_issue_graphql);
const char* g_github_mutation_create_issue_graphql_de;

//! contents of requests/github/query_pullrequests.graphql
INCBIN_EXTERN(github_query_pullrequests_graphql);
const char* g_github_query_pullrequests_graphql_de;

//! contents of requests/github/query_viewer.graphql
INCBIN_EXTERN(github_query_viewer_graphql);
const char* g_github_query_viewer_graphql_de;

//! contents of requests/github/mutation_create_pullrequest.graphql
INCBIN_EXTERN(github_mutation_create_pullrequest_graphql);
const char* g_github_mutation_create_pullrequest_graphql_de;

//! contents of requests/github/query_repositories.graphql
INCBIN_EXTERN(github_query_repositories_graphql);
const char* g_github_query_repositories_graphql_de;

//! contents of requests/github/query_owner.graphql
INCBIN_EXTERN(github_query_owner_graphql);
const char* g_github_query_owner_graphql_de;

//! contents of requests/github/query_gist.graphql
INCBIN_EXTERN(github_query_gist_graphql);
const char* g_github_query_gist_graphql_de;

//! contents of requests/github/query_user.graphql
INCBIN_EXTERN(github_query_user_graphql);
const char* g_github_query_user_graphql_de;

//! contents of requests/github/query_issues.graphql
INCBIN_EXTERN(github_query_issues_graphql);
const char* g_github_query_issues_graphql_de;

//! contents of requests/github/mutation_create_repository.graphql
INCBIN_EXTERN(github_mutation_create_repository_graphql);
const char* g_github_mutation_create_repository_graphql_de;

//! contents of requests/github/query_repository.graphql
INCBIN_EXTERN(github_query_repository_graphql);
const char* g_github_query_repository_graphql_de;


#endif // GEARS_REQUESTS_GITHUB_GRAPHQL_H_INC

