//! git-gears-c's REST queries
//! as structures and snprintf-style functions
//! DO NOT EDIT - this file is autogenerated.
//! Run `genie generate` or `make generate` to re-generate.

#include "github_restutils.h"
#include "stb_printf.h"

int snprintUrl_GithubMutationCreateGistRoute(char* buf, int count, const char* endpointUrl)
{
	return stbsp_snprintf(buf, count, "%s/gists", endpointUrl);
}

int snprintRestJson_GithubMutationCreateGistJson(char* buf, int count, const GithubMutationCreateGistJson* vars)
{
	return stbsp_snprintf(buf, count,
						  "{"
						  "	\"description\": \"%s -- %s\","
						  "	\"public\": \"%s\","
						  "	\"files\": {"
						  "		\"$_filename\": {"
						  "			\"content\": \"%s\","
						  "		}"
						  "	}"
						  "}"
						  "",
						  vars->title, vars->description, vars->isPublic, vars->body);
}
