//! git-gears-c's GraphQL queries
//! as structures and snprintf-style functions
//! DO NOT EDIT - this file is autogenerated.
//! Run `genie generate` or `make generate` to re-generate.

#ifndef GEARS_REQUESTS_GITLAB_GRAPHQLUTILS_H_INC
#define GEARS_REQUESTS_GITLAB_GRAPHQLUTILS_H_INC

#include <stdbool.h>

//! query data
typedef struct GitlabQueryIssueGraphql
{
	const char* fullPath;
	const char* iid;
} GitlabQueryIssueGraphql;

//! snprint variables JSON
int snprintJsonVars_GitlabQueryIssueGraphql(char* buf, int count, const GitlabQueryIssueGraphql* vars);

//! snprint request JSON
int snprintJsonRequest_GitlabQueryIssueGraphql(char* buf, int count, const GitlabQueryIssueGraphql* vars);

//! query data
typedef struct GitlabQueryGistsGraphql
{
	int count;
} GitlabQueryGistsGraphql;

//! snprint variables JSON
int snprintJsonVars_GitlabQueryGistsGraphql(char* buf, int count, const GitlabQueryGistsGraphql* vars);

//! snprint request JSON
int snprintJsonRequest_GitlabQueryGistsGraphql(char* buf, int count, const GitlabQueryGistsGraphql* vars);

//! query data
typedef struct GitlabQueryPullrequestGraphql
{
	const char* branch;
	const char* fullPath;
} GitlabQueryPullrequestGraphql;

//! snprint variables JSON
int snprintJsonVars_GitlabQueryPullrequestGraphql(char* buf, int count, const GitlabQueryPullrequestGraphql* vars);

//! snprint request JSON
int snprintJsonRequest_GitlabQueryPullrequestGraphql(char* buf, int count, const GitlabQueryPullrequestGraphql* vars);

//! query data
typedef struct GitlabQueryPullrequestsGraphql
{
	int count;
	const char* fullPath;
} GitlabQueryPullrequestsGraphql;

//! snprint variables JSON
int snprintJsonVars_GitlabQueryPullrequestsGraphql(char* buf, int count, const GitlabQueryPullrequestsGraphql* vars);

//! snprint request JSON
int snprintJsonRequest_GitlabQueryPullrequestsGraphql(char* buf, int count, const GitlabQueryPullrequestsGraphql* vars);

//! query data
typedef struct GitlabMutationCreateGistGraphql
{
	const char* body;
	const char* description;
	const char* filename;
	const char* fullPath;
	const char* mutationId;
	const char* title;
	const char* visibility;
} GitlabMutationCreateGistGraphql;

//! snprint variables JSON
int snprintJsonVars_GitlabMutationCreateGistGraphql(char* buf, int count, const GitlabMutationCreateGistGraphql* vars);

//! snprint request JSON
int snprintJsonRequest_GitlabMutationCreateGistGraphql(char* buf, int count,
													   const GitlabMutationCreateGistGraphql* vars);

//! query data
typedef struct GitlabQueryRepositoriesGraphql
{
	int count;
	const char* owner;
} GitlabQueryRepositoriesGraphql;

//! snprint variables JSON
int snprintJsonVars_GitlabQueryRepositoriesGraphql(char* buf, int count, const GitlabQueryRepositoriesGraphql* vars);

//! snprint request JSON
int snprintJsonRequest_GitlabQueryRepositoriesGraphql(char* buf, int count, const GitlabQueryRepositoriesGraphql* vars);

//! snprint request JSON
int snprintJsonRequest_GitlabQueryCurrentuserGraphql(char* buf, int count);

//! query data
typedef struct GitlabQueryGistGraphql
{
	const char* gid;
} GitlabQueryGistGraphql;

//! snprint variables JSON
int snprintJsonVars_GitlabQueryGistGraphql(char* buf, int count, const GitlabQueryGistGraphql* vars);

//! snprint request JSON
int snprintJsonRequest_GitlabQueryGistGraphql(char* buf, int count, const GitlabQueryGistGraphql* vars);

//! query data
typedef struct GitlabQueryIssuesGraphql
{
	int count;
	const char* fullPath;
} GitlabQueryIssuesGraphql;

//! snprint variables JSON
int snprintJsonVars_GitlabQueryIssuesGraphql(char* buf, int count, const GitlabQueryIssuesGraphql* vars);

//! snprint request JSON
int snprintJsonRequest_GitlabQueryIssuesGraphql(char* buf, int count, const GitlabQueryIssuesGraphql* vars);

//! query data
typedef struct GitlabQueryRepositoryGraphql
{
	const char* fullPath;
} GitlabQueryRepositoryGraphql;

//! snprint variables JSON
int snprintJsonVars_GitlabQueryRepositoryGraphql(char* buf, int count, const GitlabQueryRepositoryGraphql* vars);

//! snprint request JSON
int snprintJsonRequest_GitlabQueryRepositoryGraphql(char* buf, int count, const GitlabQueryRepositoryGraphql* vars);


#endif // GEARS_REQUESTS_GITLAB_GRAPHQLUTILS_H_INC
