//! git-gears-c's GraphQL queries, as static data buffers.
//! DO NOT EDIT - this file is autogenerated.
//! Run `genie embed` or `make embed` to re-generate.

#ifndef GEARS_REQUESTS_GITLAB_GRAPHQL_H_INC
#define GEARS_REQUESTS_GITLAB_GRAPHQL_H_INC

#define INCBIN_PREFIX g_
#define INCBIN_STYLE INCBIN_STYLE_SNAKE
#include "incbin.h"

//! contents of requests/gitlab/query_issue.graphql
INCBIN_EXTERN(gitlab_query_issue_graphql);
const char* g_gitlab_query_issue_graphql_de;

//! contents of requests/gitlab/query_gists.graphql
INCBIN_EXTERN(gitlab_query_gists_graphql);
const char* g_gitlab_query_gists_graphql_de;

//! contents of requests/gitlab/query_pullrequest.graphql
INCBIN_EXTERN(gitlab_query_pullrequest_graphql);
const char* g_gitlab_query_pullrequest_graphql_de;

//! contents of requests/gitlab/query_pullrequests.graphql
INCBIN_EXTERN(gitlab_query_pullrequests_graphql);
const char* g_gitlab_query_pullrequests_graphql_de;

//! contents of requests/gitlab/mutation_create_gist.graphql
INCBIN_EXTERN(gitlab_mutation_create_gist_graphql);
const char* g_gitlab_mutation_create_gist_graphql_de;

//! contents of requests/gitlab/query_repositories.graphql
INCBIN_EXTERN(gitlab_query_repositories_graphql);
const char* g_gitlab_query_repositories_graphql_de;

//! contents of requests/gitlab/query_currentuser.graphql
INCBIN_EXTERN(gitlab_query_currentuser_graphql);
const char* g_gitlab_query_currentuser_graphql_de;

//! contents of requests/gitlab/query_gist.graphql
INCBIN_EXTERN(gitlab_query_gist_graphql);
const char* g_gitlab_query_gist_graphql_de;

//! contents of requests/gitlab/query_issues.graphql
INCBIN_EXTERN(gitlab_query_issues_graphql);
const char* g_gitlab_query_issues_graphql_de;

//! contents of requests/gitlab/query_repository.graphql
INCBIN_EXTERN(gitlab_query_repository_graphql);
const char* g_gitlab_query_repository_graphql_de;


#endif // GEARS_REQUESTS_GITLAB_GRAPHQL_H_INC

