//! git-gears-c's GraphQL queries, as static data buffers.
//! DO NOT EDIT - this file is autogenerated.
//! Run `genie embed` or `make embed` to re-generate.

#define INCBIN_PREFIX g_
#define INCBIN_STYLE INCBIN_STYLE_SNAKE
#include "incbin.h"

INCBIN(gitlab_query_issue_graphql, "requests/gitlab/query_issue.graphql");
const char* g_gitlab_query_issue_graphql_de = "\\nquery ($_fullPath: ID!, $_iid: String!)\\n{\\n project(fullPath: $_fullPath)\\n {\\n  id,\\n  name,\\n  webUrl,\\n  issue(iid: $_iid)\\n  {\\n   iid,\\n   title,\\n   description,\\n   webUrl,\\n  }\\n }\\n}\\n";

INCBIN(gitlab_query_gists_graphql, "requests/gitlab/query_gists.graphql");
const char* g_gitlab_query_gists_graphql_de = "\\nquery($_count: Int!)\\n{\\n currentUser\\n {\\n  snippets(first: $_count)\\n  {\\n   nodes\\n   {\\n    id,\\n    title,\\n    description,\\n    createdAt,\\n    updatedAt,\\n    fileName,\\n    content,\\n    webUrl,\\n   }\\n  }\\n }\\n}\\n";

INCBIN(gitlab_query_pullrequest_graphql, "requests/gitlab/query_pullrequest.graphql");
const char* g_gitlab_query_pullrequest_graphql_de = "\\nquery ($_fullPath: ID!, $_branch: String!)\\n{\\n project(fullPath: $_fullPath)\\n {\\n  id,\\n  name,\\n  webUrl,\\n  mergeRequests(filter:{targetBranch: $_branch})\\n  {\\n   nodes\\n   {\\n    id,\\n    targetBranch,\\n    sourceBranch,\\n    iid,\\n    description,\\n    mergeStatus,\\n    title,\\n    webUrl,\\n   }\\n  }\\n }\\n}\\n";

INCBIN(gitlab_query_pullrequests_graphql, "requests/gitlab/query_pullrequests.graphql");
const char* g_gitlab_query_pullrequests_graphql_de = "\\nquery ($_fullPath: ID!, $_count: Int!)\\n{\\n project(fullPath: $_fullPath)\\n {\\n  id,\\n  name,\\n  webUrl,\\n  mergeRequests(first: $_count)\\n  {\\n   nodes\\n   {\\n    id,\\n    targetBranch,\\n    sourceBranch,\\n    iid,\\n    description,\\n    mergeStatus,\\n    title,\\n    webUrl,\\n   }\\n  }\\n }\\n}\\n";

INCBIN(gitlab_mutation_create_gist_graphql, "requests/gitlab/mutation_create_gist.graphql");
const char* g_gitlab_mutation_create_gist_graphql_de = "\\nmutation($_mutationId: String!, $_title: String!, $_body: String!, $_visibility: VisibilityLevelsEnum!, $_description: String, $_filename: String, $_fullPath: ID)\\n{\\n createSnippet(input: {\\n  clientMutationId: $_mutationId,\\n  title: $_title,\\n  fileName: $_filename,\\n  description: $_description,\\n  visibilityLevel: $_visibility,\\n  content: $_body,\\n  projectPath: $_fullPath,\\n })\\n {\\n  clientMutationId,\\n  snippet\\n  {\\n   id,\\n   title,\\n   description,\\n   createdAt,\\n   updatedAt,\\n   fileName,\\n   content,\\n   webUrl,\\n  }\\n }\\n}\\n";

INCBIN(gitlab_query_repositories_graphql, "requests/gitlab/query_repositories.graphql");
const char* g_gitlab_query_repositories_graphql_de = "\\nquery($_owner: ID!, $_count: Int!)\\n{\\n namespace(fullPath: $_owner)\\n {\\n  projects(first: $_count)\\n  {\\n   nodes\\n   {\\n    id,\\n    webUrl,\\n    name,\\n    description,\\n    fullPath,\\n    createdAt,\\n    lastActivityAt,\\n   }\\n  }\\n }\\n}\\n";

INCBIN(gitlab_query_currentuser_graphql, "requests/gitlab/query_currentuser.graphql");
const char* g_gitlab_query_currentuser_graphql_de = "\\nquery\\n{\\n currentUser\\n {\\n  username,\\n  name\\n }\\n}\\n";

INCBIN(gitlab_query_gist_graphql, "requests/gitlab/query_gist.graphql");
const char* g_gitlab_query_gist_graphql_de = "\\nquery($_gid: ID!)\\n{\\n currentUser\\n {\\n  snippets(ids: [$_gid])\\n  {\\n   nodes\\n   {\\n    id,\\n    title,\\n    description,\\n    createdAt,\\n    updatedAt,\\n    fileName,\\n    content,\\n    webUrl,\\n   }\\n  }\\n }\\n}\\n";

INCBIN(gitlab_query_issues_graphql, "requests/gitlab/query_issues.graphql");
const char* g_gitlab_query_issues_graphql_de = "\\nquery ($_fullPath: ID!, $_count: Int!)\\n{\\n project(fullPath: $_fullPath)\\n {\\n  id,\\n  name,\\n  webUrl,\\n  issues(first: $_count)\\n  {\\n   nodes\\n   {\\n    iid,\\n    title,\\n    description,\\n    webUrl,\\n   }\\n  }\\n }\\n}\\n";

INCBIN(gitlab_query_repository_graphql, "requests/gitlab/query_repository.graphql");
const char* g_gitlab_query_repository_graphql_de = "\\nquery($_fullPath: ID!)\\n{\\n project(fullPath: $_fullPath)\\n {\\n  id,\\n  webUrl,\\n  name,\\n  description,\\n  fullPath,\\n  createdAt,\\n  lastActivityAt,\\n }\\n}\\n";

