//! git-gears-c's GraphQL queries
//! as structures and snprintf-style functions
//! DO NOT EDIT - this file is autogenerated.
//! Run `genie generate` or `make generate` to re-generate.

#include "gitlab_graphqlutils.h"
#include "github_graphql.h"
#include "gitlab_graphql.h"
#include "stb_printf.h"

int snprintJsonVars_GitlabQueryIssueGraphql(char* buf, int count, const GitlabQueryIssueGraphql* vars)
{
	return stbsp_snprintf(buf, count,
						  "{"
						  " \"_fullPath\": \"%s\","
						  " \"_iid\": \"%s\""
						  "}",
						  vars->fullPath, vars->iid);
}

int snprintJsonRequest_GitlabQueryIssueGraphql(char* buf, int count, const GitlabQueryIssueGraphql* vars)
{
	return stbsp_snprintf(buf, count,
						  "{"
						  "\"variables\": {"
						  " \"_fullPath\": \"%s\","
						  " \"_iid\": \"%s\""
						  "}"
						  ","
						  "\"query\": \"%s\""
						  "} \n",
						  vars->fullPath, vars->iid, g_gitlab_query_issue_graphql_de);
}

int snprintJsonVars_GitlabQueryGistsGraphql(char* buf, int count, const GitlabQueryGistsGraphql* vars)
{
	return stbsp_snprintf(buf, count,
						  "{"
						  " \"_count\": %i"
						  "}",
						  vars->count);
}

int snprintJsonRequest_GitlabQueryGistsGraphql(char* buf, int count, const GitlabQueryGistsGraphql* vars)
{
	return stbsp_snprintf(buf, count,
						  "{"
						  "\"variables\": {"
						  " \"_count\": %i"
						  "}"
						  ","
						  "\"query\": \"%s\""
						  "} \n",
						  vars->count, g_gitlab_query_gists_graphql_de);
}

int snprintJsonVars_GitlabQueryPullrequestGraphql(char* buf, int count, const GitlabQueryPullrequestGraphql* vars)
{
	return stbsp_snprintf(buf, count,
						  "{"
						  " \"_branch\": \"%s\","
						  " \"_fullPath\": \"%s\""
						  "}",
						  vars->branch, vars->fullPath);
}

int snprintJsonRequest_GitlabQueryPullrequestGraphql(char* buf, int count, const GitlabQueryPullrequestGraphql* vars)
{
	return stbsp_snprintf(buf, count,
						  "{"
						  "\"variables\": {"
						  " \"_branch\": \"%s\","
						  " \"_fullPath\": \"%s\""
						  "}"
						  ","
						  "\"query\": \"%s\""
						  "} \n",
						  vars->branch, vars->fullPath, g_gitlab_query_pullrequest_graphql_de);
}

int snprintJsonVars_GitlabQueryPullrequestsGraphql(char* buf, int count, const GitlabQueryPullrequestsGraphql* vars)
{
	return stbsp_snprintf(buf, count,
						  "{"
						  " \"_count\": %i,"
						  " \"_fullPath\": \"%s\""
						  "}",
						  vars->count, vars->fullPath);
}

int snprintJsonRequest_GitlabQueryPullrequestsGraphql(char* buf, int count, const GitlabQueryPullrequestsGraphql* vars)
{
	return stbsp_snprintf(buf, count,
						  "{"
						  "\"variables\": {"
						  " \"_count\": %i,"
						  " \"_fullPath\": \"%s\""
						  "}"
						  ","
						  "\"query\": \"%s\""
						  "} \n",
						  vars->count, vars->fullPath, g_gitlab_query_pullrequests_graphql_de);
}

int snprintJsonVars_GitlabMutationCreateGistGraphql(char* buf, int count, const GitlabMutationCreateGistGraphql* vars)
{
	return stbsp_snprintf(buf, count,
						  "{"
						  " \"_body\": \"%s\","
						  " \"_description\": \"%s\","
						  " \"_filename\": \"%s\","
						  " \"_fullPath\": \"%s\","
						  " \"_mutationId\": \"%s\","
						  " \"_title\": \"%s\","
						  " \"_visibility\": \"%s\""
						  "}",
						  vars->body, vars->description, vars->filename, vars->fullPath, vars->mutationId, vars->title,
						  vars->visibility);
}

int snprintJsonRequest_GitlabMutationCreateGistGraphql(char* buf, int count,
													   const GitlabMutationCreateGistGraphql* vars)
{
	return stbsp_snprintf(buf, count,
						  "{"
						  "\"variables\": {"
						  " \"_body\": \"%s\","
						  " \"_description\": \"%s\","
						  " \"_filename\": \"%s\","
						  " \"_fullPath\": \"%s\","
						  " \"_mutationId\": \"%s\","
						  " \"_title\": \"%s\","
						  " \"_visibility\": \"%s\""
						  "}"
						  ","
						  "\"query\": \"%s\""
						  "} \n",
						  vars->body, vars->description, vars->filename, vars->fullPath, vars->mutationId, vars->title,
						  vars->visibility, g_gitlab_mutation_create_gist_graphql_de);
}

int snprintJsonVars_GitlabQueryRepositoriesGraphql(char* buf, int count, const GitlabQueryRepositoriesGraphql* vars)
{
	return stbsp_snprintf(buf, count,
						  "{"
						  " \"_count\": %i,"
						  " \"_owner\": \"%s\""
						  "}",
						  vars->count, vars->owner);
}

int snprintJsonRequest_GitlabQueryRepositoriesGraphql(char* buf, int count, const GitlabQueryRepositoriesGraphql* vars)
{
	return stbsp_snprintf(buf, count,
						  "{"
						  "\"variables\": {"
						  " \"_count\": %i,"
						  " \"_owner\": \"%s\""
						  "}"
						  ","
						  "\"query\": \"%s\""
						  "} \n",
						  vars->count, vars->owner, g_gitlab_query_repositories_graphql_de);
}

int snprintJsonRequest_GitlabQueryCurrentuserGraphql(char* buf, int count)
{
	return stbsp_snprintf(buf, count,
						  "{"
						  "\"query\": \"%s\""
						  "} \n",
						  g_gitlab_query_currentuser_graphql_de);
}

int snprintJsonVars_GitlabQueryGistGraphql(char* buf, int count, const GitlabQueryGistGraphql* vars)
{
	return stbsp_snprintf(buf, count,
						  "{"
						  " \"_gid\": \"%s\""
						  "}",
						  vars->gid);
}

int snprintJsonRequest_GitlabQueryGistGraphql(char* buf, int count, const GitlabQueryGistGraphql* vars)
{
	return stbsp_snprintf(buf, count,
						  "{"
						  "\"variables\": {"
						  " \"_gid\": \"%s\""
						  "}"
						  ","
						  "\"query\": \"%s\""
						  "} \n",
						  vars->gid, g_gitlab_query_gist_graphql_de);
}

int snprintJsonVars_GitlabQueryIssuesGraphql(char* buf, int count, const GitlabQueryIssuesGraphql* vars)
{
	return stbsp_snprintf(buf, count,
						  "{"
						  " \"_count\": %i,"
						  " \"_fullPath\": \"%s\""
						  "}",
						  vars->count, vars->fullPath);
}

int snprintJsonRequest_GitlabQueryIssuesGraphql(char* buf, int count, const GitlabQueryIssuesGraphql* vars)
{
	return stbsp_snprintf(buf, count,
						  "{"
						  "\"variables\": {"
						  " \"_count\": %i,"
						  " \"_fullPath\": \"%s\""
						  "}"
						  ","
						  "\"query\": \"%s\""
						  "} \n",
						  vars->count, vars->fullPath, g_gitlab_query_issues_graphql_de);
}

int snprintJsonVars_GitlabQueryRepositoryGraphql(char* buf, int count, const GitlabQueryRepositoryGraphql* vars)
{
	return stbsp_snprintf(buf, count,
						  "{"
						  " \"_fullPath\": \"%s\""
						  "}",
						  vars->fullPath);
}

int snprintJsonRequest_GitlabQueryRepositoryGraphql(char* buf, int count, const GitlabQueryRepositoryGraphql* vars)
{
	return stbsp_snprintf(buf, count,
						  "{"
						  "\"variables\": {"
						  " \"_fullPath\": \"%s\""
						  "}"
						  ","
						  "\"query\": \"%s\""
						  "} \n",
						  vars->fullPath, g_gitlab_query_repository_graphql_de);
}
